site_title: Meu Portal
author: Jefferson Rodrigues de Oliveira
email: jefferson.rodrigues@ifsp.edu.br
css: https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css
javascript: https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js
home:
  html: content/home/home.html
disciplinas:
- disciplina: Mecânica Clássica
  aulas:
  - name: Aula 01 - Cinemática
    html: content/aulas/mecanica-classica/aula-01/aula-01.html
    pdf: https://drive.google.com/file/d/1V1e0EN5j0cUmlBZCL6b1w03uWnQv8RXV/view?usp=drivesdk
  - name: Aula 02 - Dinâmica
    html: content/aulas/mecanica-classica/aula-02/aula-02.html
    pdf: https://drive.google.com/file/d/1K8d-eHmzYgv8QMaxg--QYahkno0Hj7XD/view?usp=drivesdk
  - name: Aula 03 - Dinâmica
    html: content/aulas/mecanica-classica/aula-03/aula-03.html
    pdf: https://drive.google.com/file/d/148Y3x5B_OyNfOo9XQnfGTjNmJ89i4Wjn/view?usp=drivesdk
  - name: Aula 04 - Dinâmica
    html: content/aulas/mecanica-classica/aula-04/aula-04.html
    pdf: https://drive.google.com/file/d/1Dx-es4Ijwh5myxiKYLMF6FxzXDlVAdmJ/view?usp=drivesdk
  - name: Aula 05 - Dinâmica
    html: content/aulas/mecanica-classica/aula-05/aula-05.html
    pdf: https://drive.google.com/file/d/1Rz_RfIMuZoQVLinOhfMuB1quctPsXaqy/view?usp=drivesdk
- disciplina: Termologia
  aulas:
  - name: Aula 01 - Introdução
    html: content/aulas/termologia/aula-01/termo-1.html
    pdf: https://drive.google.com/file/d/1V1e0EN5j0cUmlBZCL6b1w03uWnQv8RXV/view?usp=drivesdk
- disciplina: Eletromagnetismo
  aulas:
  - name: Aula 01 - Campo Elétrico
    html: content/aulas/eletromagnetismo/aula-01/aula-01.html
    pdf: https://drive.google.com/file/d/1zll3QPjX0pC4VXQlGM7FDYLqn6_40j0t/view?usp=drivesdk
- disciplina: Ondas
  aulas:
  - name: Aula 01 - Introdução à Ondulatória
    html: content/aulas/ondas/aula-01/ondas-01.html
    pdf: https://drive.google.com/file/d/1V1e0EN5j0cUmlBZCL6b1w03uWnQv8RXV/view?usp=drivesdk
blog:
  posts:
  - title: Introdução à Teoria da Relatividade
    date: 25/01/2025
    html: content/blog/relatividade/introducao.html
    pdf: https://drive.google.com/file/d/1ulXn51wFP9-ZCv8-f9FbChuiGoMSykNt/view?usp=drivesdk
  - title: O Paradoxo do Gato de Schrödinger
    date: 24/11/2024
    html: content/blog/quantica/gato-schrodinger.html
    pdf: https://drive.google.com/file/d/1n0Vgzzsi-DV3-_2Yms5ztqniy1s8BDMk/view?usp=drivesdk
  - title: Algoritmos Quânticos
    date: 01/02/2025
    html: content/blog/computacao/algoritmos-quanticos.html
    pdf: https://drive.google.com/file/d/1wavsDpjQ-UEiPhpwJ4VUxpid1Gyg8STC/view?usp=drivesdk
  - title: Óptica
    date: 23/01/2026
    html: content/blog/optica-geometrica/opt-3.html
    pdf: https://drive.google.com/file/d/1wavsDpjQ-UEiPhpwJ4VUxpid1Gyg8STC/view?usp=drivesdk
