site_title: "Meu Portal"
author: "Jefferson Rodrigues de Oliveira"
email: "jefferson.rodrigues@ifsp.edu.br"
css: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
javascript: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"

home:
  html: "content/home/home.html"
  
disciplinas:
  - disciplina: "Termodinâmica 1"
    aulas:
      - name: "Aula 01 - Conceitos Iniciais"
        html: "/home/jefferson/Documentos/GitHubPages/novo-portal/content/aulas/EM-Termo1/termo1-aula-01.html"
        pdf: "/home/jefferson/Documentos/Gdrive/gdrive/pdf-GitHubPages/aulas/EM-Termo1/termo1-aula-01.pdf"

  - disciplina: "Física Moderna 1"
    aulas:
      - name: "Aula 01 - Concepções Históricas"
        html: "/home/jefferson/Documentos/GitHubPages/novo-portal/content/aulas/ES-FM1/fmi1-aula-01.html"
        pdf: "/home/jefferson/Documentos/Gdrive/gdrive/pdf-GitHubPages/aulas/ES-FM1/fmi1-aula-01.pdf"

blog:
  posts:
    - title: "Algoritmos Quânticos"
      date: "01/02/2025"
      html: "/home/jefferson/Documentos/GitHubPages/novo-portal/content/blog/computacão/algoritmos-quânticos.html"
      pdf: "/home/jefferson/Documentos/Gdrive/gdrive/pdf-GitHubPages/blog/computacão/algoritmos-quânticos.pdf"

