site_title: "Meu Portal"
author: "Jefferson Rodrigues de Oliveira"
email: "jefferson.rodrigues@ifsp.edu.br"
css: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
javascript: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"

home:
  html: "content/home/home.html"
  
disciplinas:
  - disciplina: "Termodinâmica 1"
    aulas:
      - name: "Aula 01 - Conceitos Iniciais"
        html: "content/aulas/EM-Termo1/Aula-01/termo1-aula-01.html"
        pdf: "https://drive.google.com/file/d/1kxr2MRukFEOscdmmH0-JRXcGjSaLzb1Q/view?usp=drive_link" 
      - name: "Aula 02 - Escalas Termométricas"
        html: "content/aulas/EM-Termo1/Aula-02/termo1-aula-02.html"
        pdf: "https://drive.google.com/file/d/1SMKy_yDz66XZ-aH1R35iCJ8mAyt28PsZ/view?usp=drive_link" 
      - name: "Aula 03 - Variação entre Escalas Termométricas e Escalas Arbitrárias"
        html: "content/aulas/EM-Termo1/Aula-03/termo1-aula-03.html"
        pdf: "https://drive.google.com/file/d/1VBTwE__4T5X-AlBBJK-rpu8e84GdUF9D/view?usp=drive_link" 

  - disciplina: "Física Moderna 1"
    aulas:
      - name: "Aula 01 - Concepções Históricas"
        html: "content/aulas/ES-FM1/Aula-01/fmi-aula-01.html"
        pdf: "https://drive.google.com/file/d/1HVOpUChU1AqMkq-2gqXbgfrzgjvJVo7r/view?usp=drive_link"  
      - name: "Aula 02 - Quantização da Carga: Experimentos de Thomson"
        html: "content/aulas/ES-FM1/Aula-02/fmi-aula-02.html"
        pdf: "https://drive.google.com/file/d/1sclyLmf2b4PVMojhf1FAnlKdScoOT1cQ/view?usp=drive_link" 
        
  - disciplina: "Mecânica dos Fluidos"
    aulas:
      - name: "Aula 01 - Introdução à Mecânica dos Fluidos"
        html: "content/aulas/ES-MecFlu/Aula-01/mecflu-aula-01.html"
        pdf: "https://drive.google.com/file/d/1H0WT3FRl-485VHfGQxEGAGe_nVGdB5nK/view?usp=drive_link" 

blog:
  posts:
    - title: "Algoritmos Quânticos"
      date: "01/02/2025"
      html: "content/blog/computacão/algoritmos-quânticos.html"
      pdf: "/home/jefferson/Documentos/Gdrive/gdrive/pdf-GitHubPages/blog/computacão/algoritmos-quânticos.pdf"

