site_title: "Portal de Física"
author: "Jefferson Rodrigues de Oliveira"
email: "jefferson.rodrigues@ifsp.edu.br"
css: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
javascript: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"

home:
  html: "content/home/home.html"
  pdf: "content/home/home.pdf"
  
disciplinas:
  - disciplina: "Mecânica Clássica"
    aulas:
      - name: "Aula 01 - Cinemática"
        html: "content/aulas/mecanica-classica/aula-01/aula-01.html"
        pdf: "content/aulas/mecanica-classica/aula-01/aula-01.pdf"
      - name: "Aula 02 - Dinâmica"
        html: "content/aulas/mecanica-classica/aula-02/aula-02.html"
        pdf: "content/aulas/mecanica-classica/aula-02/aula-02.pdf"
      - name: "Aula 03 - Dinâmica"
        html: "content/aulas/mecanica-classica/aula-03/aula-02.html"
        pdf: "content/aulas/mecanica-classica/aula-02/aula-02.pdf"
      - name: "Aula 04 - Dinâmica"
        html: "content/aulas/mecanica-classica/aula-04/aula-02.html"
        pdf: "content/aulas/mecanica-classica/aula-02/aula-02.pdf"
      - name: "Aula 05 - Dinâmica"
        html: "content/aulas/mecanica-classica/aula-05/aula-02.html"
        pdf: "content/aulas/mecanica-classica/aula-02/aula-02.pdf"

  - disciplina: "Termologia"
    aulas:
      - name: "Aula 01 - Introdução"
        html: "content/aulas/termologia/aula-01/termo-1.html"
        pdf: "content/aulas/termologia/aula-01/aula-01.pdf"

  - disciplina: "Eletromagnetismo"
    aulas:
      - name: "Aula 01 - Campo Elétrico"
        html: "content/aulas/eletromagnetismo/aula-01/aula-01.html"
        pdf: "content/aulas/eletromagnetismo/aula-01/aula-01.pdf"

  - disciplina: "Ondas"
    aulas:
      - name: "Aula 01 - Introdução à Ondulatória"
        html: "content/aulas/ondas/aula-01/ondas-01.html"
        pdf: "content/aulas/ondas/aula-01/aula-01.pdf"
blog:
  posts:
    - title: "Introdução à Teoria da Relatividade"
      date: "25/01/2025"
      html: "content/blog/relatividade/introducao.html"
      pdf: "content/blog/relatividade/introducao.pdf"
    - title: "O Paradoxo do Gato de Schrödinger"
      date: "24/11/2024"
      html: "content/blog/quantica/gato-schrodinger.html"
      pdf: "content/blog/quantica/gato-schrodinger.pdf"
    - title: "Algoritmos Quânticos"
      date: "01/02/2025"
      html: "content/blog/computacao/algoritmos-quanticos.html"
      pdf: "content/blog/computacao/algoritmos-quanticos.pdf"
    - title: "Óptica"
      date: "23/01/2026"
      html: "content/blog/optica-geometrica/opt-3.html"
      pdf: "content/blog/computacao/algoritmos-quanticos.pdf"
